name: Test and Deploy to Staging

# This pipeline will run on:
# 1. Any push to the 'staging' branch
# 2. A manual run from the "Actions" tab
on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest # This is the temporary virtual server from GitHub
    
    steps:
      # Step 1: Check out your new repo's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Securely copy the INNERMOST app code subfolder to a TEMPORARY location on server
      - name: Securely Copy App Files to Temp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          password: ${{ secrets.STAGING_SSH_PASSWORD }} # Or key
          port: 22
          source: "Task-1/one_fm_google_integration/one_fm_google_integration/" # CORRECTED SOURCE PATH (deepest level)
          target: "/tmp/deploy_app"
          rm: true

      # Step 3: Move files into place, set up bench, run tests, migrate, and restart
      - name: Deploy App and Run Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_SSH_HOST }}
          username: ${{ secrets.STAGING_SSH_USER }}
          password: ${{ secrets.STAGING_SSH_PASSWORD }} # Or use key
          port: 22
          script: |
            set -e
            
            echo "==== 1. Preparing target directory ===="
            BENCH_PATH="${{ secrets.BENCH_PATH }}"
            APP_NAME="one_fm_google_integration"
            APP_TARGET_PATH="$BENCH_PATH/apps/$APP_NAME"
            APP_SOURCE_PATH="/tmp/deploy_app" # Where scp puts the files
            
            # Ensure target directory exists and is empty before moving contents
            rm -rf "$APP_TARGET_PATH"
            mkdir -p "$APP_TARGET_PATH" 
            
            echo "==== 2. Moving app files into place ===="
            # --- START CORRECTED MV ---
            # Move the *contents* of the temp source dir into the target app dir
            # 'shopt -s dotglob' ensures hidden files (like .git) are also moved if present
            shopt -s dotglob
            mv "$APP_SOURCE_PATH"/* "$APP_TARGET_PATH"/
            shopt -u dotglob # Disable dotglob again
            # --- END CORRECTED MV ---
            
            echo "==== 3. Setting ownership and permissions ===="
            sudo chown -R frappe:frappe "$APP_TARGET_PATH"
            find "$APP_TARGET_PATH" -type d -exec chmod 755 {} \;
            find "$APP_TARGET_PATH" -type f -exec chmod 644 {} \;

            echo "==== 4. Verifying internal app structure (Debug) ===="
            echo "--- Listing contents of $APP_TARGET_PATH ---"
            ls -al "$APP_TARGET_PATH" # Use -al for more detail
            echo "--- Checking specifically for hooks.py and __init__.py ---"
            ls -l "$APP_TARGET_PATH/hooks.py" || echo "hooks.py NOT FOUND (Should be found now!)"
            ls -l "$APP_TARGET_PATH/__init__.py" || echo "__init__.py NOT FOUND (Should be found now!)"
            
            echo "==== 5. Setting PYTHONPATH ===="
            export PYTHONPATH=$BENCH_PATH/apps:$PYTHONPATH
            echo "PYTHONPATH is now: $PYTHONPATH"

            echo "==== 6. Navigating to Bench Directory ===="
            cd "$BENCH_PATH"
            
            echo "==== 7. Restarting Bench Services (Attempt 1) ===="
            sudo /home/frappe/.local/bin/bench restart
            sleep 5 

            echo "==== 8. Refreshing bench requirements ===="
            /home/frappe/.local/bin/bench setup requirements
            
            echo "==== 9. Registering the app with the site ===="
            /home/frappe/.local/bin/bench --site ${{ secrets.STAGING_SITE_NAME }} install-app "$APP_NAME"
            
            echo "==== 10. Running Unit Tests ===="
            /home/frappe/.local/bin/bench --site ${{ secrets.STAGING_SITE_NAME }} set-config allow_tests true
            /home/frappe/.local/bin/bench --site ${{ secrets.STAGING_SITE_NAME }} run-tests --app "$APP_NAME"
            
            # Step 11: Installing Python dependencies - REMOVED
            
            echo "==== 12. Running Database Migrations ===="
            /home/frappe/.local/bin/bench --site ${{ secrets.STAGING_SITE_NAME }} migrate
            
            echo "==== 13. Restarting Bench Services (Attempt 2) ===="
            sudo /home/frappe/.local/bin/bench restart
            
            echo "✅ Deployment to staging complete!"

      # Step 4: Send Success Notification (Commented Out)
      # - name: Send Success Notification
      #   if: success()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.MAIL_HOST }}
      #     server_port: ${{ secrets.MAIL_PORT }}
      #     username: ${{ secrets.MAIL_USER }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: "✅ DEPLOYMENT SUCCESS: one_fm_google_integration to Staging"
      #     to: ${{ secrets.MAIL_TO }}
      #     from: "GitHub Actions Bot <${{ secrets.MAIL_USER }}>"
      #     body: |
      #       Successfully deployed commit ${{ github.sha }} to the staging server.
      #       Commit by: ${{ github.actor }}
      #       See commit: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}

      # Step 5: Send Failure Notification (Commented Out)
      # - name: Send Failure Notification
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.MAIL_HOST }}
      #     server_port: ${{ secrets.MAIL_PORT }}
      #     username: ${{ secrets.MAIL_USER }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: "❌ DEPLOYMENT FAILED: one_fm_google_integration to Staging"
      #     to: ${{ secrets.MAIL_TO }}
      #     from: "GitHub Actions Bot <${{ secrets.MAIL_USER }}>"
      #     body: |
      #       Failed to deploy commit ${{ github.sha }} to the staging server.
            
      #       Check the pipeline log for details:
      #       ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
